---
site_name: Code With Engineering Playbook
site_url: https://microsoft.github.io/code-with-engineering-playbook
site_description: ISE Code With Engineering Playbook
site_author: Microsoft ISE

repo_url: https://github.com/microsoft/code-with-engineering-playbook/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
  palette:
    primary: black
  logo: resources/ms_icon.png
  favicon: resources/ms_icon.png
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist
