version: '3.8'
services:
  docker-in-docker:
    build:
      context: .
    network_mode: "host"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace
      # Keep command history
      - K8s-zshhistory:/root/commandhistory
      # Keep kind config
      - K8s-kindconfig:/root/.kube/
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro # does not work on Windows! Will need to generate in container :(
      # Forwarding the socket is optional, but lets docker work inside the container if you install the Docker CLI.
      # See the docker-in-docker-compose definition for details on how to install it.
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity

volumes:
  K8s-zshhistory:
  K8s-kindconfig: